
export let products = [
    {
        pic: "https://m.media-amazon.com/images/I/81tjLksKixL._AC_SL1500_.jpg",
        thumbnails: ['https://m.media-amazon.com/images/I/91QqR55XhQL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/91rx2KE8YGL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/71+JNapCNaL._AC_SL1500_.jpg'],
        name: "Seagate Portable 2TB External Hard Drive Portable HDD – USB 3.0 for PC, Mac, PlayStation, & Xbox - 1-Year Rescue Service (STGX2000400)",
        shortName: "Seagate Portable 2TB",
        desc: ['Easily store and access 2TB to content on the go with the Seagate Portable Drive, a USB external hard drive', 'Designed to work with Windows or Mac computers, this external hard drive makes backup a snap just drag and drop'],
        price: "$61.99",
        quantity: 7,
    },
    {
        pic: "https://m.media-amazon.com/images/I/71cxm1e19BL._AC_SL1500_.jpg",
        thumbnails: ['https://m.media-amazon.com/images/I/A15nymkfBZL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/81Ek8ekLOXL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/916AM42JJyL._AC_SL1500_.jpg'],
        name: "SanDisk 2TB Extreme Portable SSD - Up to 1050MB/s - USB-C, USB 3.2 Gen 2 - External Solid State Drive - SDSSDE61-2T00-G25 ",
        shortName: "SanDisk 2TB",
        desc: ['Up to 2-meter drop protection and IP55 water and dust resistance mean this tough drive can take a beating. ', 'Help keep private content private with the included password protection featuring 256‐bit AES hardware encryption. '],
        price: "$149.99",
        quantity: 12
    },
    {
        pic: "https://m.media-amazon.com/images/I/61V8wURcIaL._AC_SL1500_.jpg",
        thumbnails: ['https://m.media-amazon.com/images/I/61DyMzc0LEL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/61WtGtHnWUL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/61-ScEzBxSL._AC_SL1500_.jpg'],
        name: "128MB (NOT 128GB) 10 Pack USB Flash Drives Gradient Color USB 2.0 Memory Stick Wholesale Bulk Swivel Design Thumb Drive for Data Storage ",
        shortName: "128MB(NOT 128GB)10 Pack",
        desc: ['✔PLUG & USE: No need to install any software, the zip drive is easy to be recognized by computer, laptop, notebook, PC, car audio, speaker, smart TV, etc. ', '✔CAN BE FORMATTED: The default system format of flash drives is FAT, which is suitable for most devices, such as TVs, DVD players, cars, printers, embroidery machines, etc.'],
        price: "$15.67",
        quantity: 18,
    },
    {
        pic: "https://m.media-amazon.com/images/I/51hawKFSexL._AC_SL1000_.jpg",
        thumbnails: ['https://m.media-amazon.com/images/I/61BTHMO4T5L._AC_SL1000_.jpg', 'https://m.media-amazon.com/images/I/71cfM3PI1GL._AC_SL1000_.jpg', 'https://m.media-amazon.com/images/I/61JXnqbAjRL._AC_SL1000_.jpg'],
        name: "USB Flash Drive 1TB, STTARLUK Pen Drive Compatible with Phone/Pad External Storage USB Stick Memory Stick Compatible with Pad/Pod/Mac/Android/PC (Black, 1TB) ",
        shortName: "USB Flash Drive 1TB",
        desc: ['(HIGH SPEED FILE TRANSFERS) Directly plugs into your Phone port and USB port; 80 MB/s reading and 40 MB/s writing speed in USB end. Makes files transmission much easier on the go.', '(SHARE to SOCIAL MEDIA) Thumb jump drive share files with social medias and other apps.You Can Share document/Photo to the social media directly.(Facebook,twitter and so on)'],
        price: "$32.98",
        quantity: 4,
    },
    {
        pic: "https://m.media-amazon.com/images/I/911ujeCkGfL._AC_SL1500_.jpg",
        thumbnails: ['https://m.media-amazon.com/images/I/816LWP6S5uL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/81hZdrBZ1zL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/81fuXR-JPGL._AC_SL1500_.jpg'],
        name: "SAMSUNG 870 EVO SATA III SSD 1TB 2.5” Internal Solid State Hard Drive, Upgrade PC or Laptop Memory and Storage for IT Pros, Creators, Everyday Users, MZ-77E1T0B/AM ",
        shortName: "SAMSUNG 870",
        desc: ['THE SDD ALL-STAR: The latest 870 EVO has indisputable performance, reliability and compatibility built upon Samsung\'s pioneering technology', 'MORE COMPATIBLE THAN EVER: 870 EVO has been compatibility tested for major host systems and applications, including chipsets, motherboards, NAS, and video recording devices'],
        price: "$104.03",
        quantity: 9,
    },
    {
        pic: "https://m.media-amazon.com/images/I/61VAIygA70L._AC_SL1500_.jpg",
        thumbnails: ['https://m.media-amazon.com/images/I/61TixcdtDmL._AC_SL1000_.jpg', 'https://m.media-amazon.com/images/I/61AMdQu7d5L._AC_SL1000_.jpg', 'https://m.media-amazon.com/images/I/61usi1X+ugL._AC_SL1000_.jpg'],
        name: "Flash Drive 256GB for iPhone USB Memory Stick Thumb Drives High Speed USB Stick ,Photo Stick External Storage for iPhone/iPad/Android/PC(Pink) ",
        shortName: "Flash Drive 256GB",
        desc: ['Multi-Port usb drive:The usb stick with usb/iphone connection port/micro usb/type c (independent adapter) four interfaces,which is more convenient for data transfer between different devices, so as to get rid of the data cable and iTunes and iCloud, let you switch easily storage space. ', 'Protect Your Privacy:Use the thumb drive to easily share data with friends and colleagues, making work and entertainment more fun.At the same time you can also enable all data to be protected by password and touch ID, your privacy will not be stolen even you lose the photo storage. '],
        price: "$30.99",
        quantity: 2,
    },
    {
        pic: "https://m.media-amazon.com/images/I/61xc3Sg70nL._AC_SL1500_.jpg",
        thumbnails: ['https://m.media-amazon.com/images/I/71O8rYKR45L._AC_SL1000_.jpg', 'https://m.media-amazon.com/images/I/61GXAVMeVCL._AC_SL1000_.jpg', 'https://m.media-amazon.com/images/I/51ody+IOnJL._AC_.jpg'],
        name: "USB Flash Drive 1TB, Sttarluk Photo Stick USB Pen Drive for Phone/Pad External Storage Memory Stick Compatible with Pad/Pod/Mac/Android/PC (1TB Light Blue) ",
        shortName: "USB Flash Drive 1TB",
        desc: ['(HIGH SPEED FILE TRANSFERS) Directly plugs into your Phone port and USB port; 80 MB/s reading and 40 MB/s writing speed in USB end. Makes files transmission much easier on the go.', '(FORMAT FRIENDLY STREAMING APP) The free APP supports all major video and music formats so you can stream directly from the Phone. Saving you precious space and time. Record videos and take photos directly to the memory stick via APP '],
        price: "$30.98",
        quantity: 11,
    },
    {
        pic: "https://m.media-amazon.com/images/I/61CKrZWOcrL._AC_SL1500_.jpg",
        thumbnails: ['https://m.media-amazon.com/images/I/61DNYOd9N3L._AC_SL1200_.jpg', 'https://m.media-amazon.com/images/I/61DPcdheTeL._AC_SL1200_.jpg', 'https://m.media-amazon.com/images/I/61PlvSbqdOL._AC_SL1440_.jpg'],
        name: "SAMSUNG T7 Shield 1TB, Portable SSD, up to 1050MB/s, USB 3.2 Gen2, Rugged, IP65 Rated, for Photographers, Content Creators and Gaming, External Solid State Drive (MU-PE1T0S/AM, 2022), Black ",
        shortName: "SAMSUNG T7 Shield 1TB",
        desc: ['RUGGED DURABILITY: Tough, fast, and compact, the all new rugged PSSD T7 Shield is built to endure with the space to create thanks to an IP65 rating for Dust and Water resistance', 'All firmware and components, including Samsung\'s world- renowned DRAM and NAND, are produced in-house, allowing end-to-end integration for quality you can trust '],
        price: "$89.99",
        quantity: 1,
    },
    {
        pic: "https://m.media-amazon.com/images/I/910A6B1Sa4L._AC_SL1500_.jpg",
        thumbnails: ['https://m.media-amazon.com/images/I/812c-oYuGpL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/71do8FEZlrL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/61UbdAQaDrL._AC_SL1000_.jpg'],
        name: "Toshiba Canvio Basics 2TB Portable External Hard Drive USB 3.0, Black - HDTB420XK3AA ",
        shortName: "Toshiba Canvio Basics 2TB",
        desc: ['Sleek profile design with a matte, smudge resistance finish', 'Quickly add more storage capacity to your PC and other compatible devices'],
        price: "$59.99",
        quantity: 13,
    },
    {
        pic: "https://m.media-amazon.com/images/I/71bG7na+RZL._AC_SL1500_.jpg",
        thumbnails: ['https://m.media-amazon.com/images/I/71ztOajpEIL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/71ofw68vaBL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/61JhT1IM4qL._AC_SL1500_.jpg'],
        name: "Seagate Game Drive for Xbox 2TB External Hard Drive Portable HDD - USB 3.2 Gen 1, Black with built-in green LED bar , Xbox Certified, 3 year Rescue Services (STKX2000400) ",
        shortName: "Seagate Game Drive",
        desc: ['BUILD YOUR GAME VAULT 2TB of capacity to build the ultimate Game Vault without sacrificing titles', 'WARRANTY Enjoy peace of mind with the included 3-year Rescue Data Recovery Services and 1-year limited warranty'],
        price: " $84.99",
        quantity: 5,
    },
    {
        pic: "https://m.media-amazon.com/images/I/61N2p3aTAYL._AC_SL1500_.jpg",
        thumbnails: ['https://m.media-amazon.com/images/I/71AqMATHAnL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/51YfuYXtE0L._AC_SL1444_.jpg', 'https://m.media-amazon.com/images/I/81UviHI3TAL._AC_SL1500_.jpg'],
        name: "SanDisk 128GB Ultra Dual Drive USB Type-C - USB-C, USB 3.1 - SDDDC2-128G-G46 ",
        shortName: "SanDisk 128GB Ultra",
        desc: ['Easily transfer files between smartphones, tablets and computers', 'Free up space on your Android smartphone (Mobile device requires USB Type C port and On The Go (OTG) support)'],
        price: "$16.61",
        quantity: 6,
    },
    {
        pic: "https://m.media-amazon.com/images/I/61-kcp7fL9S._AC_SL1500_.jpg",
        thumbnails: ['https://m.media-amazon.com/images/I/81baOJc+LDL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/718MIw5haqL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/71POEX6zi1L._AC_SL1500_.jpg'],
        name: "SanDisk 32GB 3-Pack Ultra USB 3.0 Flash Drive (3x32GB) - SDCZ48-032G-GAM46T",
        shortName: "SanDisk 32GB 3-Pack",
        desc: ['Transfer speeds up to 10x faster than standard USB 2.0 drives (4MB/s); up to 130MB/s read speed; USB 3.0 port required. Based on internal testing; performance may be lower depending upon host device. 1MB=1,000,000 bytes', 'Backward compatible with USB 2.0'],
        price: "$15.99",
        quantity: 7,
    },
    {
        pic: "https://m.media-amazon.com/images/I/510+J06fz0L._AC_SL1000_.jpg",
        thumbnails: ['https://m.media-amazon.com/images/I/71+ZrUmwhhL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/919OaQdoSOL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/61jDPoB+d3L._AC_SL1500_.jpg'],
        name: "WD 5TB My Passport Portable External Hard Drive with backup software and password protection, Black - WDBPKJ0050BBK-WESN ",
        shortName: "WD 5TB",
        desc: ['Software for device management and backup with password protection. (Download and installation required. Terms and conditions apply. User account registration may be required.)', '256-bit AES hardware encryption'],
        price: "$114.89",
        quantity: 3,
    },
    {
        pic: "https://m.media-amazon.com/images/I/61RaH93te2L._AC_SL1500_.jpg",
        thumbnails: ['https://m.media-amazon.com/images/I/81ukVrtkIVL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/71ZXW1B+7vS._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/81hq8iVGrFL._AC_SL1500_.jpg'],
        name: "MFi Certified 128GB Photo-Stick-for-iPhone-Storage iPhone-Memory iPhone USB for Photos iPhone USB Flash Drive Memory for iPad External iPhone Storage iPhone Thumb Drive for iPad Photo Stick ",
        shortName: "MFi Certified 128GB",
        desc: ['(MFi CERTIFIED IPHONE USB FLASH DRIVE + MFi CERTIFIED APP = FASTLY FREE UP SPACE OF IPHONE IPAD WITH 128GB EXTERNAL STORAGE)~.~ If you have almost used up all space on your iPhone or iPad, this photo stick for iPhone helps alleviate being at full storage with 128GB. And iPhone usb for photos is also a great tool for traveling photographers editing on iPad. Using this iPhone memory product, there is no worries, no problems with the iPhone storage any more!', 'WATCH MOVIES VIEW PHOTOS PLAY MUSIC DIRECTLY FROM THE IPHONE FLASH DRIVE'],
        price: "$39.99",
        quantity: 19,
    },
    {
        pic: "https://m.media-amazon.com/images/I/712S0gBsC5L._AC_SL1500_.jpg",
        thumbnails: ['https://m.media-amazon.com/images/I/71ZqlrB-TpL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/81Trg+Ef-OL._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/I/812lOZIZXmL._AC_SL1500_.jpg'],
        name: "Seagate 16TB HDD Exos X16 7200 RPM 512e/4Kn SATA 6Gb/s 256MB Cache 3.5-Inch Enterprise Hard Drive (ST16000NM001G) ",
        shortName: "Seagate 16TB HDD",
        desc: ['PowerBalance feature optimizes IOPS/Watt', 'Seagate Secure models provide hardware-based security to help protect data-at-rest. With Instant Secure Erase, drive retirement is safe, affordable, fast and easy.'],
        price: "$289.99",
        quantity: 2,
    }
]